-- Do not edit this file if you dont know what you are doing

-- Get all stats

function PLEVELS_DATA:GetLevel(ply)
  return ply:GetNWInt('plevels_level', 1)
end

function PLEVELS_DATA:GetXP(ply)
  return ply:GetNWFloat('plevels_xp', 0)
end



if SERVER then
  function PLEVELS_DATA:SetLevel(ply, value)
    ply:SetNWInt('plevels_level', value)
  end

  function PLEVELS_DATA:SetXP(ply, value)
    ply:SetNWFloat('plevels_xp', math.Round(value, 2))
  end

  function PLEVELS_DATA:AddLevel(ply, value)
    ply:SetNWInt('plevels_level', PLEVELS_DATA:GetLevel(ply)+value)
  end

  function PLEVELS_DATA:AddXP(ply, value)
    local newXP = PLEVELS_DATA:GetXP(ply)+value
    ply:SetNWFloat('plevels_xp', math.Round(newXP, 2))
  end
end
